### ISSUE TITLE
Invalid augment statement: wrong path, missing condition

### ISSUE THREAD

**Issue by michbin** [openBackhaul/vlanFc#1]
The vlan-fc-1-0 release 2020-08-17 has an invalid `augment` statement:

- The path "/core-model:control-construct/core-model:forwarding-construct" is wrong. There is no `forwarding-construct` element in the Core Model. The path should point to the `forwarding-domain/fc` element instead.

- The `when` condition is missing. This would cause any `fc` instance to have VLAN FC properties.

**Comment by demx8as6** [comment]
2020-10-21: Solved in YANG -UML to be chacked.

**Comment by openBackhaul** [comment]
It's clear that this should be the right path in YANG
"/core-model:control-construct/core-model:forwarding-domain/core-model:fc"

but in general the content of the Specify::target stereotype looks strange and it's unclear, whether 
"/CoreModel:ControlConstruct:ControlConstruct/CoreModel:ForwardingDomain:ForwardingDomain/CoreModel:ForwardingDomain:Fc"

leads to the wished path statement.
