### ISSUE TITLE
Deleting fcIsOn and related attributes

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/vlanFc#3]
During screening results of a query it became obvious that VlanFcConfiguration::fcIsOn is not supported by any of the device models, which are participating at the TSP.

Therefore it is proposed to delete the following attributes from the VlanFc modeling:
•	VlanFcCapability::adminShutDownIsAvail
•	VlanFcConfiguration::fcIsOn

**Comment by demx8as6** [comment]
2020-10-21: Agreed as proposed!
