### ISSUE TITLE
VlanFcConfiguration::fcName wrong Default Value

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/vlanFc#4]
Currently, Default Value of  VlanFcConfiguration::fcName is "Interface name not yet defined."

Proposal:
To change Default Value to "VLAN name not yet defined."

**Comment by openBackhaul** [comment]
Decision:
Change Default Value to "VLAN name not yet defined."

**Comment by demx8as6** [comment]
YANG was corrected in revision 2021-02-07.
Issue can be closed.
